import type { Config } from "tailwindcss";

const preset: Partial<Config> = {
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#321113",
        "error-container": "#ffdad6",
        "secondary-fixed": "#ffe088",
        "on-secondary-container": "#745c00",
        "on-primary-fixed": "#3d1516",
        "on-primary-container": "#5c2324",
        "surface-dim": "#dbdad6",
        surface: "#faf9f5",
        "outline-variant": "#d2c3c3",
        "primary-fixed": "#f9e0e0",
        outline: "#5c4f4f",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e3e2df",
        "on-secondary-fixed": "#241a00",
        background: "#faf9f5",
        "surface-container-high": "#e9e8e4",
        "on-tertiary-container": "#835455",
        "on-secondary-fixed-variant": "#574500",
        "on-primary-fixed-variant": "#5c2324",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f2f1ed",
        "tertiary-fixed": "#ffdad9",
        secondary: "#735c00",
        error: "#ba1a1a",
        tertiary: "#805253",
        "on-secondary": "#ffffff",
        "inverse-primary": "#e8b8b9",
        "primary-container": "#f4e4e4",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#f3b8b8",
        "secondary-fixed-dim": "#e9c349",
        "primary-fixed-dim": "#e4bcbc",
        "surface-container-low": "#f4f4f0",
        "on-primary": "#ffffff",
        "surface-variant": "#e3e2df",
        "on-error": "#ffffff",
        "on-surface": "#1b1c1a",
        "surface-tint": "#7c2c2e",
        "surface-container": "#efeeea",
        "on-tertiary-fixed-variant": "#653b3c",
        primary: "#7c2c2e",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fed65b",
        "on-surface-variant": "#3a3333",
        "text-muted": "#4a4242",
        "on-background": "#1b1c1a",
        "tertiary-container": "#ffd1d1",
        "surface-bright": "#faf9f5",
        "chip-border": "#e8d5c4",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "80px",
        "container-max": "1200px",
        "section-gap": "120px",
        "margin-mobile": "20px",
        gutter: "24px",
        unit: "8px",
      },
      fontFamily: {
        display: ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        body: ["var(--font-outfit)", "Outfit", "sans-serif"],
        "headline-sm": ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        "display-lg-mobile": ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        "display-lg": ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        "label-caps": ["var(--font-outfit)", "Outfit", "sans-serif"],
        "headline-md": ["var(--font-bodoni)", "Bodoni Moda", "serif"],
        "body-lg": ["var(--font-outfit)", "Outfit", "sans-serif"],
        "body-md": ["var(--font-outfit)", "Outfit", "sans-serif"],
      },
      fontSize: {
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "display-lg-mobile": ["40px", { lineHeight: "1.2", fontWeight: "400" }],
        "display-lg": [
          "64px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "400" },
        ],
        "label-caps": [
          "12px",
          { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "600" },
        ],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "body-lg": [
          "18px",
          { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
      maxWidth: {
        "container-max": "1200px",
      },
    },
  },
};

export default preset;
